# Generated by Django 3.1.3 on 2020-11-19 18:27

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('inner_username', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('first_name', 'last_name'), unique=True, verbose_name='slug')),
                ('role', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('start_work', models.DateField(null=True)),
                ('end_work', models.DateField(null=True)),
                ('wage', models.IntegerField(null=True)),
                ('TeamMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teammember')),
            ],
        ),
    ]
