# Generated by Django 3.1.3 on 2020-11-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='end_work',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='start_work',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='wage',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
