# Generated by Django 3.1.3 on 2020-11-25 15:53

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201125_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='inner_username',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('first_name', 'last_name'), verbose_name='slug'),
        ),
    ]
