# Generated by Django 3.1.3 on 2020-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201125_1616'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teammember',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
