# Generated by Django 3.1.3 on 2020-11-25 18:03

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201125_1726'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teammember',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
