# Generated by Django 3.1.3 on 2020-11-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201125_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
