# Generated by Django 3.1.3 on 2020-11-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201125_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='inner_username',
        ),
    ]
